// import { Task, TaskCategory, TaskPriority, User } from "./types";

// // Dummy User
// export const dummyUser: User = {
//   id: "user-123",
//   username: "johndoe",
//   name: "John Doe",
//   avatar_url: "https://example.com/avatar.jpg",
//   bio: "A passionate developer and productivity enthusiast.",
// };

// // Dummy Tasks
// export const dummyTasks: Task[] = [
//   {
//     id: "task-001",
//     title: "Finish the project report",
//     description: "Complete the financial summary and email it to the manager.",
//     isCompleted: true,
//     category: TaskCategory.Work,
//     dueDate: new Date("2025-06-20"),
//     priority: TaskPriority.High,
//   },
//   {
//     id: "task-002",
//     title: "Buy groceries",
//     description: "Milk, eggs, bread, and fruits",
//     isCompleted: false,
//     category: TaskCategory.Shopping,
//     dueDate: new Date("2025-06-15"),
//     priority: TaskPriority.Medium,
//   },
//   {
//     id: "task-003",
//     title: "Morning Run",
//     description: "Run 5 kilometers in the park",
//     isCompleted: true,
//     category: TaskCategory.Health,
//     dueDate: new Date("2025-06-13"),
//     priority: TaskPriority.Low,
//   },
//   {
//     id: "task-004",
//     title: "Read TypeScript documentation",
//     isCompleted: false,
//     category: TaskCategory.Learning,
//     dueDate: new Date("2025-06-18"),
//     priority: TaskPriority.Medium,
//   },
//   {
//     id: "task-005",
//     title: "Pay electricity bill",
//     description: "Before the due date to avoid late fees",
//     isCompleted: false,
//     category: TaskCategory.Finance,
//     dueDate: new Date("2025-06-16"),
//     priority: TaskPriority.High,
//   },
//   {
//     id: "task-0014",
//     title: "Finish the project report",
//     description: "Complete the financial summary and email it to the manager.",
//     isCompleted: true,
//     category: TaskCategory.Work,
//     dueDate: new Date("2025-06-20"),
//     priority: TaskPriority.High,
//   },
//   {
//     id: "task-0012",
//     title: "Buy groceries",
//     description: "Milk, eggs, bread, and fruits",
//     isCompleted: false,
//     category: TaskCategory.Shopping,
//     dueDate: new Date("2025-06-15"),
//     priority: TaskPriority.Medium,
//   },
//   {
//     id: "task-0013",
//     title: "Morning Run",
//     description: "Run 5 kilometers in the park",
//     isCompleted: true,
//     category: TaskCategory.Health,
//     dueDate: new Date("2025-06-13"),
//     priority: TaskPriority.Low,
//   },
//   {
//     id: "task-0010",
//     title: "Read TypeScript documentation",
//     isCompleted: false,
//     category: TaskCategory.Learning,
//     dueDate: new Date("2025-06-18"),
//     priority: TaskPriority.Medium,
//   },
//   {
//     id: "task-0011",
//     title: "Pay electricity bill",
//     description: "Before the due date to avoid late fees",
//     isCompleted: false,
//     category: TaskCategory.Finance,
//     dueDate: new Date("2025-06-16"),
//     priority: TaskPriority.High,
//   },
// ];
